//! oxblocks -- a memory-safe Monero block explorer for monerod.

mod api;
mod config;
mod html;
mod tree_paths;

use std::sync::Arc;

use axum::Router;
use axum::http::{HeaderName, HeaderValue, StatusCode};
use axum::routing::get;
use clap::Parser;
use tower::ServiceBuilder;
use tower_http::LatencyUnit;
use tower_http::catch_panic::CatchPanicLayer;
use tower_http::compression::CompressionLayer;
use tower_http::limit::RequestBodyLimitLayer;
use tower_http::set_header::SetResponseHeaderLayer;
use tower_http::timeout::TimeoutLayer;
use tower_http::trace::{DefaultOnResponse, TraceLayer};
use tracing_subscriber::EnvFilter;

use crate::api::handlers::{self, AppState};
use crate::config::Config;

/// Response headers applied to every response, including the ones generated by
/// the middleware rather than by a route.
///
/// The explorer serves no scripts, loads no external assets, sets no cookies
/// and embeds no images, so the policy can be `default-src 'none'` with a
/// single narrow exception for our own stylesheet. Anything that later needs a
/// wider policy is a design change, not a header change.
fn security_headers() -> [(HeaderName, HeaderValue); 5] {
    [
        (
            HeaderName::from_static("content-security-policy"),
            HeaderValue::from_static(
                "default-src 'none'; style-src 'self'; form-action 'self'; \
                 base-uri 'none'; frame-ancestors 'none'",
            ),
        ),
        (
            HeaderName::from_static("x-content-type-options"),
            HeaderValue::from_static("nosniff"),
        ),
        (
            HeaderName::from_static("referrer-policy"),
            HeaderValue::from_static("no-referrer"),
        ),
        (
            HeaderName::from_static("x-frame-options"),
            HeaderValue::from_static("DENY"),
        ),
        (
            HeaderName::from_static("permissions-policy"),
            HeaderValue::from_static("interest-cohort=(), browsing-topics=()"),
        ),
    ]
}

fn router(config: &Config, state: Arc<AppState>) -> Router {
    let app = Router::new()
        .route("/api/version", get(handlers::version))
        .route("/api/block/{id}", get(handlers::block))
        .route("/api/transaction/{hash}", get(handlers::transaction))
        .route(
            "/api/transaction/{hash}/paths",
            get(handlers::transaction_paths),
        )
        .route("/api/rawblock/{id}", get(handlers::raw_block))
        .route("/api/rawtransaction/{hash}", get(handlers::raw_transaction))
        .route("/api/feeestimate", get(handlers::fee_estimate))
        .route("/api/transactions", get(handlers::transactions))
        .route("/api/mempool", get(handlers::mempool))
        .route("/api/search/{query}", get(handlers::search))
        .route("/api/networkinfo", get(handlers::network_info))
        // k-anonymous lookups
        .route("/api/blocks/{start}/{end}", get(handlers::blocks_range))
        .route(
            "/api/transaction/private/{postfix}",
            get(handlers::transaction_private),
        )
        .route(
            "/api/transactions/recent",
            get(handlers::transactions_recent),
        )
        // HTML
        .route("/", get(html::index))
        .route("/api", get(html::api_docs))
        .route("/page/{page}", get(html::page_at))
        .route("/block/{id}", get(html::block))
        .route("/tx/{hash}", get(html::transaction))
        .route("/tx/{hash}/fcmp", get(html::fcmp_proof))
        .route("/tx/{hash}/paths", get(html::tree_paths))
        .route("/mempool", get(html::mempool))
        .route("/altblocks", get(html::alt_blocks))
        .route("/search", get(html::search))
        .route("/static/style.css", get(html::stylesheet))
        .route("/health", get(health))
        .fallback(html::not_found)
        .with_state(state)
        .route(
            "/robots.txt",
            // An explorer mirrors public data, so there is nothing to gain
            // from being crawled, and crawlers are expensive here because
            // every page costs RPC calls.
            get(|| async { "User-agent: *\nDisallow: /\n" }),
        );

    // One limit for the whole server. `Router::layer` wraps each route in the
    // layer on its own, so a limit the layer built would be one per route;
    // the semaphore is made here, once, and every route's copy shares it.
    let slots = Arc::new(tokio::sync::Semaphore::new(config.max_concurrent));

    let mut app = app.layer(
        ServiceBuilder::new()
            // Outermost of the middleware: a panic in a handler becomes a
            // 500 for that one request instead of killing the connection
            // task. This does not excuse panics -- it bounds them.
            .layer(CatchPanicLayer::new())
            .layer(
                TraceLayer::new_for_http()
                    .on_response(DefaultOnResponse::new().latency_unit(LatencyUnit::Millis)),
            )
            // These responses are mostly hex, which compresses to a fraction
            // of its size -- the k-anonymous set is a thousand transactions of
            // it. Applied only for a client that sends `Accept-Encoding`, and
            // only above a small size floor.
            //
            // gzip, deflate and brotli. Deliberately **not** zstd: the
            // `zstd` crate wraps the C library, and linking C to serve a block
            // explorer is the thing this project exists to avoid.
            //
            // What is linked instead, checked rather than assumed: `flate2`
            // resolves to the `miniz_oxide` backend (two `unsafe` blocks, and
            // `forbid(unsafe_code)` on the rest of it) -- its C bindings are a
            // different backend and are not compiled. The `brotli` crate's
            // `unsafe` is all in `src/ffi`, its C-ABI *export* layer, which is
            // behind a feature nothing here enables, and in its own binary.
            // Zero C, and no `unsafe` on the path a request takes.
            //
            // Compressing a response is safe to do here in a way it would not
            // be on an authenticated site: every page is public, there are no
            // cookies, no session and no secrets, so a compressed length
            // cannot reveal one (the BREACH/CRIME family of attacks needs a
            // secret in the response to find).
            .layer(
                CompressionLayer::new()
                    .gzip(true)
                    .deflate(true)
                    .br(true)
                    .no_zstd(),
            )
            // 504 rather than 408: when this fires it is almost always the
            // daemon being slow, not the client being slow.
            .layer(TimeoutLayer::with_status_code(
                StatusCode::GATEWAY_TIMEOUT,
                config.request_timeout(),
            ))
            .layer(axum::middleware::from_fn_with_state(slots, within_limit))
            .layer(RequestBodyLimitLayer::new(config.max_body_bytes)),
    );

    // Applied outermost, so that a response this explorer did not render still
    // carries them: a request body over the limit, a timeout, a panic caught
    // below. Those bodies are short and inert, but "every response" is the
    // claim, and a header stack that stops at the routes does not make it.
    for (name, value) in security_headers() {
        app = app.layer(SetResponseHeaderLayer::overriding(name, value));
    }

    app
}

/// The routes that never reach the daemon, served outside `--max-concurrent`
/// so that a slow daemon filling every slot cannot fail them too.
const OUTSIDE_THE_LIMIT: [&str; 3] = ["/health", "/static/style.css", "/robots.txt"];

/// Run the request once a slot of `--max-concurrent` is free.
///
/// The slot is waited for inside the request's future, under the request
/// timeout, so a request queued behind a full server is shed by the timeout
/// like one waiting on anything else.
async fn within_limit(
    axum::extract::State(slots): axum::extract::State<Arc<tokio::sync::Semaphore>>,
    request: axum::extract::Request,
    next: axum::middleware::Next,
) -> axum::response::Response {
    use axum::response::IntoResponse as _;
    if OUTSIDE_THE_LIMIT.contains(&request.uri().path()) {
        return next.run(request).await;
    }
    let Ok(_slot) = slots.acquire_owned().await else {
        return StatusCode::SERVICE_UNAVAILABLE.into_response();
    };
    next.run(request).await
}

/// Liveness, plus cache occupancy.
///
/// The cache is the only state this process holds, so its hit counts are the
/// one operational number worth exposing. Deliberately says nothing about the
/// daemon: a health check that fails when the daemon is slow turns one
/// degraded dependency into an outage.
async fn health(
    axum::extract::State(state): api::handlers::Shared,
) -> impl axum::response::IntoResponse {
    let caches: serde_json::Map<String, serde_json::Value> = state
        .chain
        .cache_stats()
        .into_iter()
        .chain([
            ("tree_paths", state.paths.stats()),
            ("recent_tree_paths", state.paths.recent_stats()),
            ("table_rows", state.rows.stats()),
        ])
        .map(|(name, s)| {
            (
                name.to_owned(),
                serde_json::json!({
                    "len": s.len,
                    "capacity": s.capacity,
                    "hits": s.hits,
                    "misses": s.misses,
                }),
            )
        })
        .collect();

    let body = serde_json::json!({
        "status": "ok",
        "version": env!("CARGO_PKG_VERSION"),
        // Outbound calls, not cache misses: one /get_transactions carrying
        // forty hashes is forty misses and one call.
        "rpc_calls": state.chain.rpc_calls(),
        "caches": caches,
    });

    // Rendered by hand rather than with axum's Json extractor, so the crate
    // keeps its narrow feature set -- the API layer emits JSON the same way.
    (
        [(
            axum::http::header::CONTENT_TYPE,
            "application/json; charset=utf-8",
        )],
        serde_json::to_string(&body).unwrap_or_else(|_| r#"{"status":"ok"}"#.to_owned()),
    )
}

/// Resolves when the process is asked to stop, so in-flight requests finish
/// rather than being cut off mid-response.
async fn shutdown_signal() {
    let ctrl_c = async {
        let _ = tokio::signal::ctrl_c().await;
    };

    #[cfg(unix)]
    let terminate = async {
        match tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate()) {
            Ok(mut sig) => {
                sig.recv().await;
            }
            Err(e) => tracing::warn!("cannot listen for SIGTERM: {e}"),
        }
    };

    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();

    tokio::select! {
        () = ctrl_c => tracing::info!("received ctrl-c, shutting down"),
        () = terminate => tracing::info!("received SIGTERM, shutting down"),
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let config = Config::parse();
    // Before anything is served, because a pair of bounds that refuses every
    // request is better found here than by the first caller.
    let limits = config.limits()?;

    // Before the first request: the stylesheet is built once and cached by
    // browsers for a day.
    html::set_theme(config.theme);

    tracing_subscriber::fmt()
        .with_env_filter(EnvFilter::try_new(&config.log)?)
        .init();

    let node = monerod_rpc::Client::builder(&config.daemon_url)
        .timeout(config.rpc_timeout())
        .max_response_bytes(config.max_response_bytes())
        .user_agent(concat!("oxblocks/", env!("CARGO_PKG_VERSION")))
        .build()?;

    tracing::info!(daemon = %node.base_url(), "connecting to monerod");

    // Fail at startup rather than on the first request, and say plainly which
    // pages a restricted daemon would remove.
    let state = Arc::new(AppState {
        chain: explorer_core::RpcChainSource::new(node)
            .with_max_inflight_rpc(config.max_inflight_rpc),
        limits,
        paths: tree_paths::PathCache::default(),
        recent: Default::default(),
        rows: Default::default(),
    });
    match state.chain.info().await {
        Ok(info) => {
            tracing::info!(
                nettype = %info.nettype,
                height = info.height,
                restricted = info.restricted,
                "connected to monerod {}",
                info.version
            );
            if info.restricted {
                tracing::warn!(
                    "this daemon is restricted: /get_transaction_pool, \
                     get_alternate_chains and get_alt_blocks_hashes are blocked, \
                     so the mempool and alt-block pages will be unavailable"
                );
            }
        }
        Err(e) => tracing::warn!("could not reach monerod at startup: {e}"),
    }

    // The curve-tree generators take a second or two to decode, so do it now
    // rather than in the first request to check a path.
    tokio::task::spawn_blocking(|| {
        let started = std::time::Instant::now();
        explorer_core::curve_tree::load_generators();
        tracing::info!("curve-tree generators loaded in {:?}", started.elapsed());
    });

    let listener = tokio::net::TcpListener::bind(config.bind).await?;
    tracing::info!(addr = %config.bind, "oxblocks listening");

    axum::serve(listener, router(&config, state))
        .with_graceful_shutdown(shutdown_signal())
        .await?;

    Ok(())
}

#[cfg(test)]
mod tests {
    #![allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::indexing_slicing,
        clippy::cast_possible_truncation,
        clippy::cast_precision_loss,
        clippy::cast_sign_loss
    )]

    use super::*;

    /// Points at a closed port: these tests exercise routing and headers, not
    /// the daemon.
    fn test_state() -> Arc<AppState> {
        state_with(crate::config::Limits::default())
    }

    fn state_with(limits: crate::config::Limits) -> Arc<AppState> {
        Arc::new(AppState {
            chain: explorer_core::RpcChainSource::new(
                monerod_rpc::Client::new("http://127.0.0.1:1").expect("valid url"),
            ),
            limits,
            paths: crate::tree_paths::PathCache::default(),
            recent: Default::default(),
            rows: Default::default(),
        })
    }

    /// The limit is the server's, not each route's; a request waiting for a
    /// slot is shed by the timeout; and the routes that never reach the
    /// daemon are answered while a slow one holds every slot.
    #[tokio::test]
    async fn a_slow_daemon_fills_the_limit_but_not_health() {
        use axum::body::Body;
        use axum::http::Request;
        use tower::ServiceExt;

        // A daemon that never answers, counting who reaches it.
        let daemon = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let url = format!("http://{}", daemon.local_addr().unwrap());
        let reached = Arc::new(std::sync::atomic::AtomicUsize::new(0));
        let counted = Arc::clone(&reached);
        tokio::spawn(async move {
            let mut held = Vec::new();
            while let Ok((c, _)) = daemon.accept().await {
                counted.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
                held.push(c);
            }
        });
        let reached = move || reached.load(std::sync::atomic::Ordering::SeqCst);
        let state = Arc::new(AppState {
            chain: explorer_core::RpcChainSource::new(monerod_rpc::Client::new(&url).unwrap()),
            limits: crate::config::Limits::default(),
            paths: crate::tree_paths::PathCache::default(),
            recent: Default::default(),
            rows: Default::default(),
        });
        let config = Config::parse_from([
            "oxblocks",
            "--max-concurrent",
            "1",
            "--request-timeout-secs",
            "1",
        ]);
        let app = router(&config, state);
        let ask = |uri: &'static str| {
            let app = app.clone();
            async move {
                app.oneshot(Request::builder().uri(uri).body(Body::empty()).unwrap())
                    .await
                    .unwrap()
                    .status()
            }
        };

        let slow = tokio::spawn(ask("/"));
        tokio::time::sleep(std::time::Duration::from_millis(100)).await;
        let started = std::time::Instant::now();
        assert_eq!(ask("/health").await, StatusCode::OK);
        assert_eq!(ask("/static/style.css").await, StatusCode::OK);
        assert!(started.elapsed() < std::time::Duration::from_millis(500));

        // Another route waits for the one slot, not reaching the daemon
        // while the slow request holds it.
        let before = reached();
        assert!(before > 0);
        let waiting = tokio::spawn(ask("/api/version"));
        tokio::time::sleep(std::time::Duration::from_millis(300)).await;
        assert_eq!(reached(), before);
        assert_eq!(slow.await.unwrap(), StatusCode::GATEWAY_TIMEOUT);
        assert_eq!(waiting.await.unwrap(), StatusCode::GATEWAY_TIMEOUT);
    }

    #[test]
    fn security_headers_deny_everything_by_default() {
        let headers = security_headers();
        let csp = headers
            .iter()
            .find(|(n, _)| n.as_str() == "content-security-policy")
            .map(|(_, v)| v.to_str().unwrap_or_default().to_owned())
            .unwrap_or_default();

        // If a future change needs scripts or remote assets, this test should
        // fail and force that to be a deliberate decision.
        assert!(csp.contains("default-src 'none'"));
        assert!(!csp.contains("unsafe-inline"));
        assert!(!csp.contains("unsafe-eval"));
        assert!(!csp.contains("http:"));
        assert!(!csp.contains("https:"));
    }

    /// Every route that takes user input must answer in this explorer's own
    /// voice. `/page/{page}` was declared `Path<u64>`, so axum rejected a bad
    /// one itself with a `text/plain` 400 quoting the input back -- inert,
    /// because the type is text and `nosniff` is set, but it reflected raw
    /// input and was the only route that did not render our error page.
    #[tokio::test]
    async fn a_bad_page_number_gets_this_explorers_error_page() {
        use axum::body::Body;
        use axum::http::Request;
        use tower::ServiceExt;

        let config = Config::parse_from(["oxblocks"]);
        for bad in [
            "/page/%3Cscript%3E",
            "/page/abc",
            "/page/99999999999999999999",
        ] {
            let response = router(&config, test_state())
                .oneshot(
                    Request::builder()
                        .uri(bad)
                        .body(Body::empty())
                        .expect("request builds"),
                )
                .await
                .expect("router responds");

            assert_eq!(
                response.status(),
                StatusCode::NOT_FOUND,
                "{bad} was rejected by the framework rather than answered"
            );
            let content_type = response
                .headers()
                .get(axum::http::header::CONTENT_TYPE)
                .and_then(|v| v.to_str().ok())
                .unwrap_or_default()
                .to_owned();
            assert!(
                content_type.starts_with("text/html"),
                "{bad} answered {content_type}"
            );

            let body = axum::body::to_bytes(response.into_body(), 1 << 20)
                .await
                .expect("body reads");
            let body = String::from_utf8_lossy(&body);
            assert!(
                body.contains("<!DOCTYPE html>"),
                "{bad} did not render a page"
            );
            assert!(
                !body.contains("<script>"),
                "{bad} reflected its input unescaped"
            );
        }
    }

    #[tokio::test]
    async fn health_and_robots_respond_and_carry_security_headers() {
        use axum::body::Body;
        use axum::http::Request;
        use tower::ServiceExt;

        let config = Config::parse_from(["oxblocks"]);

        let response = router(&config, test_state())
            .oneshot(
                Request::builder()
                    .uri("/health")
                    .body(Body::empty())
                    .expect("request builds"),
            )
            .await
            .expect("router responds");

        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            response
                .headers()
                .get("x-content-type-options")
                .and_then(|v| v.to_str().ok()),
            Some("nosniff"),
            "security headers must be applied to every response"
        );
        assert!(response.headers().get("content-security-policy").is_some());
    }

    /// The headers have to survive a response no route produced. A body over
    /// the limit is rejected by middleware sitting outside the router, so
    /// before the header stack was moved outermost this answer carried none of
    /// them.
    #[tokio::test]
    async fn a_middleware_rejection_carries_the_security_headers_too() {
        use axum::body::Body;
        use axum::http::Request;
        use tower::ServiceExt;

        let config = Config::parse_from(["oxblocks"]);
        let oversized = vec![b'x'; config.max_body_bytes + 1];

        let response = router(&config, test_state())
            .oneshot(
                Request::builder()
                    .method("GET")
                    .uri("/health")
                    .header(axum::http::header::CONTENT_LENGTH, oversized.len())
                    .body(Body::from(oversized))
                    .expect("request builds"),
            )
            .await
            .expect("router responds");

        assert_eq!(
            response.status(),
            StatusCode::PAYLOAD_TOO_LARGE,
            "the body limit should have rejected this before routing"
        );
        assert_eq!(
            response
                .headers()
                .get("x-content-type-options")
                .and_then(|v| v.to_str().ok()),
            Some("nosniff")
        );
        assert!(response.headers().get("content-security-policy").is_some());
    }

    async fn get(uri: &str) -> (StatusCode, String) {
        get_with(test_state(), uri).await
    }

    async fn get_with(state: Arc<AppState>, uri: &str) -> (StatusCode, String) {
        use axum::body::Body;
        use axum::http::Request;
        use tower::ServiceExt;

        let config = Config::parse_from(["oxblocks"]);
        let response = router(&config, state)
            .oneshot(
                Request::builder()
                    .uri(uri)
                    .body(Body::empty())
                    .expect("request builds"),
            )
            .await
            .expect("router responds");

        let status = response.status();
        let body = axum::body::to_bytes(response.into_body(), 1 << 20)
            .await
            .expect("body reads");
        (status, String::from_utf8_lossy(&body).into_owned())
    }

    /// An argument is read as given or refused. It is never repaired first.
    ///
    /// `1,23` was previously stripped to `123` and answered as that block, so
    /// a caller who mistyped a height got a confident answer about a different
    /// one.
    #[tokio::test]
    async fn a_malformed_argument_is_refused_rather_than_cleaned_up() {
        let hash = "a".repeat(64);
        for uri in [
            "/api/block/1,23",
            "/api/block/1%2C23",
            "/api/block/+12",
            "/api/block/%2012",
            "/api/block/0x12",
            &format!("/api/transaction/{}", "a".repeat(63)),
            &format!("/api/transaction/{}g", "a".repeat(63)),
            &format!("/api/transaction/{hash}-"),
            &format!("/api/search/{}g", "a".repeat(63)),
            "/api/blocks/1,0/5",
            "/api/blocks/1/5e2",
            "/api/transactions?limit=abc",
            "/api/transactions?page=-1",
            "/api/mempool?limit=",
            "/api/search/1,23",
        ] {
            let (status, body) = get(uri).await;
            assert_eq!(
                status,
                StatusCode::BAD_REQUEST,
                "{uri} answered {status} with {body}"
            );
            assert!(body.contains(r#""status":"fail""#), "{uri} said {body}");
        }
    }

    /// A request axum's own extractors cannot read is refused in the API's
    /// envelope too, not in axum's plain text.
    #[tokio::test]
    async fn a_request_axum_cannot_read_is_refused_in_the_envelope() {
        for uri in [
            "/api/transactions?page=1&page=2",
            "/api/mempool?limit=1&limit=2",
            "/api/feeestimate?grace_blocks=1&grace_blocks=2",
            "/api/transaction/private/%FF%FE",
            "/api/block/%FF",
            "/api/blocks/%FF/1",
        ] {
            let (status, body) = get(uri).await;
            assert_eq!(
                status,
                StatusCode::BAD_REQUEST,
                "{uri} answered {status} with {body}"
            );
            let body: serde_json::Value = serde_json::from_str(&body)
                .unwrap_or_else(|_| panic!("{uri} did not answer JSON: {body}"));
            assert_eq!(body["status"], "fail", "{uri}");
            assert!(
                body["data"]["title"]
                    .as_str()
                    .is_some_and(|t| !t.is_empty()),
                "{uri}"
            );
        }
    }

    /// The refusal above is about the argument, not about the daemon being
    /// unreachable: a well formed argument gets past the parse and fails
    /// later, with a different code.
    #[tokio::test]
    async fn a_well_formed_argument_reaches_the_daemon() {
        for uri in [
            "/api/block/123",
            &format!("/api/transaction/{}", "a".repeat(64)),
        ] {
            let (status, _) = get(uri).await;
            assert_eq!(
                status,
                StatusCode::BAD_GATEWAY,
                "{uri} should have been refused by the daemon, not by the parser"
            );
        }
    }

    /// A cap is a refusal, not a silent clamp. Asking for 999 and being given
    /// 50 without being told is the same class of surprise as `1,23`.
    #[tokio::test]
    async fn a_limit_past_the_cap_is_refused_rather_than_clamped() {
        let (status, body) = get("/api/transactions?limit=999").await;
        assert_eq!(status, StatusCode::BAD_REQUEST);
        assert!(body.contains("at most 50"), "{body}");

        let (status, body) = get("/api/mempool?limit=501").await;
        assert_eq!(status, StatusCode::BAD_REQUEST);
        assert!(body.contains("at most 500"), "{body}");
    }

    /// The pages parse the same way, and answer in their own voice.
    #[tokio::test]
    async fn the_pages_refuse_a_malformed_argument_too() {
        for uri in ["/block/1,23", "/tx/1,23", "/page/1,23"] {
            let (status, body) = get(uri).await;
            assert_eq!(status, StatusCode::NOT_FOUND, "{uri} answered {status}");
            assert!(
                body.contains("<!DOCTYPE html>"),
                "{uri} did not render a page"
            );
        }
    }

    /// An argument is echoed back to say what was refused, and a long one is
    /// cut short rather than reflected whole.
    #[tokio::test]
    async fn a_refusal_echoes_a_bounded_amount_of_the_argument() {
        let (status, body) = get(&format!("/api/block/{}", "9".repeat(400))).await;
        assert_eq!(status, StatusCode::BAD_REQUEST);
        assert!(
            body.contains("..."),
            "the echoed argument was not cut short"
        );
        assert!(
            body.len() < 200,
            "the whole argument came back in the message: {body}"
        );
    }

    /// The configured range cap is the one the endpoint enforces, and it is
    /// enforced on the arithmetic alone: the daemon here is unreachable, so a
    /// refusal proves no round trip was made, and a 502 proves one was.
    #[tokio::test]
    async fn the_block_range_cap_is_the_configured_one() {
        let narrow = state_with(crate::config::Limits {
            block_range: 5,
            ..Default::default()
        });

        let (status, body) = get_with(Arc::clone(&narrow), "/api/blocks/10/20").await;
        assert_eq!(status, StatusCode::BAD_REQUEST, "{body}");
        assert!(body.contains("at most 5"), "{body}");

        // The cap counts blocks, and a range is inclusive at both ends, so
        // 10 to 14 is exactly five and 10 to 15 is one too many.
        let (status, _) = get_with(Arc::clone(&narrow), "/api/blocks/10/14").await;
        assert_eq!(
            status,
            StatusCode::BAD_GATEWAY,
            "a range inside the cap should have reached the daemon"
        );
        let (status, body) = get_with(narrow, "/api/blocks/10/15").await;
        assert_eq!(status, StatusCode::BAD_REQUEST, "{body}");
        assert!(body.contains("Requested 6 blocks"), "{body}");

        // The default cap admits the range the narrow one refused.
        let (status, _) = get("/api/blocks/10/20").await;
        assert_eq!(status, StatusCode::BAD_GATEWAY);
    }

    /// The documentation page describes this deployment, not the defaults.
    #[tokio::test]
    async fn the_api_page_reports_the_configured_bounds() {
        let (_, page) = get_with(
            state_with(crate::config::Limits {
                postfix_min: 3,
                postfix_max: 7,
                block_range: 42,
                recent_blocks: 9,
            }),
            "/api",
        )
        .await;

        for shown in ["3&ndash;7", "42", "9"] {
            assert!(
                page.contains(&format!("<td class=\"num\">{shown}</td>")),
                "the page does not report {shown}"
            );
        }
        // And not the numbers it was compiled with.
        for stale in ["2&ndash;12", "100", "30"] {
            assert!(
                !page.contains(&format!("<td class=\"num\">{stale}</td>")),
                "the page still reports the built-in {stale}"
            );
        }
    }

    #[tokio::test]
    async fn unknown_paths_are_404_not_500() {
        use axum::body::Body;
        use axum::http::Request;
        use tower::ServiceExt;

        let config = Config::parse_from(["oxblocks"]);
        let response = router(&config, test_state())
            .oneshot(
                Request::builder()
                    .uri("/no/such/page")
                    .body(Body::empty())
                    .expect("request builds"),
            )
            .await
            .expect("router responds");

        assert_eq!(response.status(), StatusCode::NOT_FOUND);
    }
}
