//! oxblocks -- a memory-safe Monero block explorer for monerod.

mod api;
mod config;
mod html;

use std::sync::Arc;

use axum::Router;
use axum::http::{HeaderName, HeaderValue, StatusCode};
use axum::routing::get;
use clap::Parser;
use tower::ServiceBuilder;
use tower_http::LatencyUnit;
use tower_http::catch_panic::CatchPanicLayer;
use tower_http::compression::CompressionLayer;
use tower_http::limit::RequestBodyLimitLayer;
use tower_http::set_header::SetResponseHeaderLayer;
use tower_http::timeout::TimeoutLayer;
use tower_http::trace::{DefaultOnResponse, TraceLayer};
use tracing_subscriber::EnvFilter;

use crate::api::handlers::{self, AppState};
use crate::config::Config;

/// Response headers applied to every response, including the ones generated by
/// the middleware rather than by a route.
///
/// The explorer serves no scripts, loads no external assets, sets no cookies
/// and embeds no images, so the policy can be `default-src 'none'` with a
/// single narrow exception for our own stylesheet. Anything that later needs a
/// wider policy is a design change, not a header change.
fn security_headers() -> [(HeaderName, HeaderValue); 5] {
    [
        (
            HeaderName::from_static("content-security-policy"),
            HeaderValue::from_static(
                "default-src 'none'; style-src 'self'; form-action 'self'; \
                 base-uri 'none'; frame-ancestors 'none'",
            ),
        ),
        (
            HeaderName::from_static("x-content-type-options"),
            HeaderValue::from_static("nosniff"),
        ),
        (
            HeaderName::from_static("referrer-policy"),
            HeaderValue::from_static("no-referrer"),
        ),
        (
            HeaderName::from_static("x-frame-options"),
            HeaderValue::from_static("DENY"),
        ),
        (
            HeaderName::from_static("permissions-policy"),
            HeaderValue::from_static("interest-cohort=(), browsing-topics=()"),
        ),
    ]
}

fn router(config: &Config, state: Arc<AppState>) -> Router {
    let app = Router::new()
        .route("/api/version", get(handlers::version))
        .route("/api/block/{id}", get(handlers::block))
        .route("/api/transaction/{hash}", get(handlers::transaction))
        .route("/api/rawblock/{id}", get(handlers::raw_block))
        .route("/api/rawtransaction/{hash}", get(handlers::raw_transaction))
        .route("/api/feeestimate", get(handlers::fee_estimate))
        .route("/api/transactions", get(handlers::transactions))
        .route("/api/mempool", get(handlers::mempool))
        .route("/api/search/{query}", get(handlers::search))
        .route("/api/networkinfo", get(handlers::network_info))
        // k-anonymous lookups, from upstream devel
        .route("/api/blocks/{start}/{end}", get(handlers::blocks_range))
        .route(
            "/api/transaction/private/{postfix}",
            get(handlers::transaction_private),
        )
        .route(
            "/api/transactions/recent",
            get(handlers::transactions_recent),
        )
        // HTML
        .route("/", get(html::index))
        .route("/api", get(html::api_docs))
        .route("/page/{page}", get(html::page_at))
        .route("/block/{id}", get(html::block))
        .route("/tx/{hash}", get(html::transaction))
        .route("/mempool", get(html::mempool))
        .route("/altblocks", get(html::alt_blocks))
        .route("/search", get(html::search))
        .route("/static/style.css", get(html::stylesheet))
        .route("/health", get(health))
        .fallback(html::not_found)
        .with_state(state)
        .route(
            "/robots.txt",
            // The C++ explorer ships the same policy. An explorer is a mirror
            // of public data; there is nothing to gain from being crawled, and
            // crawlers are expensive here because every page costs RPC calls.
            get(|| async { "User-agent: *\nDisallow: /\n" }),
        );

    let mut app = app.layer(
        ServiceBuilder::new()
            // Outermost of the middleware: a panic in a handler becomes a
            // 500 for that one request instead of killing the connection
            // task. This does not excuse panics -- it bounds them.
            .layer(CatchPanicLayer::new())
            .layer(
                TraceLayer::new_for_http()
                    .on_response(DefaultOnResponse::new().latency_unit(LatencyUnit::Millis)),
            )
            // These responses are mostly hex, which compresses to a fraction
            // of its size -- the k-anonymous set is a thousand transactions of
            // it. Applied only for a client that sends `Accept-Encoding`, and
            // only above a small size floor.
            //
            // gzip, deflate and brotli. Deliberately **not** zstd: the
            // `zstd` crate wraps the C library, and linking C to serve a block
            // explorer is the thing this project exists to avoid.
            //
            // What is linked instead, checked rather than assumed: `flate2`
            // resolves to the `miniz_oxide` backend (two `unsafe` blocks, and
            // `forbid(unsafe_code)` on the rest of it) -- its C bindings are a
            // different backend and are not compiled. The `brotli` crate's
            // `unsafe` is all in `src/ffi`, its C-ABI *export* layer, which is
            // behind a feature nothing here enables, and in its own binary.
            // Zero C, and no `unsafe` on the path a request takes.
            //
            // Compressing a response is safe to do here in a way it would not
            // be on an authenticated site: every page is public, there are no
            // cookies, no session and no secrets, so a compressed length
            // cannot reveal one (the BREACH/CRIME family of attacks needs a
            // secret in the response to find).
            .layer(
                CompressionLayer::new()
                    .gzip(true)
                    .deflate(true)
                    .br(true)
                    .no_zstd(),
            )
            .layer(RequestBodyLimitLayer::new(config.max_body_bytes))
            // 504 rather than 408: when this fires it is almost always the
            // upstream daemon being slow, not the client being slow.
            .layer(TimeoutLayer::with_status_code(
                StatusCode::GATEWAY_TIMEOUT,
                config.request_timeout(),
            ))
            .concurrency_limit(config.max_concurrent),
    );

    // Applied outermost, so that a response this explorer did not render still
    // carries them: a request body over the limit, a timeout, a panic caught
    // below. Those bodies are short and inert, but "every response" is the
    // claim, and a header stack that stops at the routes does not make it.
    for (name, value) in security_headers() {
        app = app.layer(SetResponseHeaderLayer::overriding(name, value));
    }

    app
}

/// Liveness, plus cache occupancy.
///
/// The cache is the only state this process holds, so its hit counts are the
/// one operational number worth exposing. Deliberately says nothing about the
/// daemon: a health check that fails when an upstream is slow turns one
/// degraded dependency into an outage.
async fn health(
    axum::extract::State(state): api::handlers::Shared,
) -> impl axum::response::IntoResponse {
    let caches: serde_json::Map<String, serde_json::Value> = state
        .chain
        .cache_stats()
        .into_iter()
        .map(|(name, s)| {
            (
                name.to_owned(),
                serde_json::json!({
                    "len": s.len,
                    "capacity": s.capacity,
                    "hits": s.hits,
                    "misses": s.misses,
                }),
            )
        })
        .collect();

    let body = serde_json::json!({
        "status": "ok",
        "version": env!("CARGO_PKG_VERSION"),
        // Outbound calls, not cache misses: one /get_transactions carrying
        // forty hashes is forty misses and one call.
        "rpc_calls": state.chain.rpc_calls(),
        "caches": caches,
    });

    // Rendered by hand rather than with axum's Json extractor, so the crate
    // keeps its narrow feature set -- the API layer emits JSON the same way.
    (
        [(
            axum::http::header::CONTENT_TYPE,
            "application/json; charset=utf-8",
        )],
        serde_json::to_string(&body).unwrap_or_else(|_| r#"{"status":"ok"}"#.to_owned()),
    )
}

/// Resolves when the process is asked to stop, so in-flight requests finish
/// rather than being cut off mid-response.
async fn shutdown_signal() {
    let ctrl_c = async {
        let _ = tokio::signal::ctrl_c().await;
    };

    #[cfg(unix)]
    let terminate = async {
        match tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate()) {
            Ok(mut sig) => {
                sig.recv().await;
            }
            Err(e) => tracing::warn!("cannot listen for SIGTERM: {e}"),
        }
    };

    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();

    tokio::select! {
        () = ctrl_c => tracing::info!("received ctrl-c, shutting down"),
        () = terminate => tracing::info!("received SIGTERM, shutting down"),
    }
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let config = Config::parse();

    tracing_subscriber::fmt()
        .with_env_filter(EnvFilter::try_new(&config.log)?)
        .init();

    let node = monerod_rpc::Client::builder(&config.daemon_url)
        .timeout(config.rpc_timeout())
        .user_agent(concat!("oxblocks/", env!("CARGO_PKG_VERSION")))
        .build()?;

    tracing::info!(daemon = %node.base_url(), "connecting to monerod");

    // Fail at startup rather than on the first request, and say plainly which
    // pages a restricted daemon would remove.
    let state = Arc::new(AppState {
        chain: explorer_core::RpcChainSource::new(node)
            .with_max_inflight_rpc(config.max_inflight_rpc),
        txids_loose: std::sync::atomic::AtomicBool::new(false),
    });
    match state.chain.info().await {
        Ok(info) => {
            tracing::info!(
                nettype = %info.nettype,
                height = info.height,
                restricted = info.restricted,
                "connected to monerod {}",
                info.version
            );
            // The k-anonymous lookup needs get_txids_loose, which is in
            // monerod master and release-v0.19 but in no release build. Say so
            // at startup rather than letting the first caller discover it.
            let loose = state.chain.supports_txids_loose().await;
            // Recorded so /api can say whether *this* deployment serves the
            // k-anonymous lookup, without probing again on every page view.
            state
                .txids_loose
                .store(loose, std::sync::atomic::Ordering::Relaxed);
            if loose {
                tracing::info!(
                    "daemon provides get_txids_loose: /api/transaction/private is available"
                );
            } else {
                tracing::warn!(
                    "this daemon has no get_txids_loose, so /api/transaction/private \
                     will refuse requests. It is in monerod master and release-v0.19 \
                     but in no release build; v0.18.x does not have it. Every other \
                     endpoint, including /api/blocks, works normally."
                );
            }

            if info.restricted {
                tracing::warn!(
                    "this daemon is restricted: /get_transaction_pool, \
                     get_alternate_chains and get_alt_blocks_hashes are blocked, \
                     so the mempool and alt-block pages will be unavailable"
                );
            }
        }
        Err(e) => tracing::warn!("could not reach monerod at startup: {e}"),
    }

    let listener = tokio::net::TcpListener::bind(config.bind).await?;
    tracing::info!(addr = %config.bind, "oxblocks listening");

    axum::serve(listener, router(&config, state))
        .with_graceful_shutdown(shutdown_signal())
        .await?;

    Ok(())
}

#[cfg(test)]
mod tests {
    #![allow(
        clippy::unwrap_used,
        clippy::expect_used,
        clippy::indexing_slicing,
        clippy::cast_possible_truncation,
        clippy::cast_precision_loss,
        clippy::cast_sign_loss
    )]

    use super::*;

    /// Points at a closed port: these tests exercise routing and headers, not
    /// the daemon.
    fn test_state() -> Arc<AppState> {
        Arc::new(AppState {
            chain: explorer_core::RpcChainSource::new(
                monerod_rpc::Client::new("http://127.0.0.1:1").expect("valid url"),
            ),
            txids_loose: std::sync::atomic::AtomicBool::new(false),
        })
    }

    #[test]
    fn security_headers_deny_everything_by_default() {
        let headers = security_headers();
        let csp = headers
            .iter()
            .find(|(n, _)| n.as_str() == "content-security-policy")
            .map(|(_, v)| v.to_str().unwrap_or_default().to_owned())
            .unwrap_or_default();

        // If a future change needs scripts or remote assets, this test should
        // fail and force that to be a deliberate decision.
        assert!(csp.contains("default-src 'none'"));
        assert!(!csp.contains("unsafe-inline"));
        assert!(!csp.contains("unsafe-eval"));
        assert!(!csp.contains("http:"));
        assert!(!csp.contains("https:"));
    }

    /// Every route that takes user input must answer in this explorer's own
    /// voice. `/page/{page}` was declared `Path<u64>`, so axum rejected a bad
    /// one itself with a `text/plain` 400 quoting the input back -- inert,
    /// because the type is text and `nosniff` is set, but it reflected raw
    /// input and was the only route that did not render our error page.
    #[tokio::test]
    async fn a_bad_page_number_gets_this_explorers_error_page() {
        use axum::body::Body;
        use axum::http::Request;
        use tower::ServiceExt;

        let config = Config::parse_from(["oxblocks"]);
        for bad in [
            "/page/%3Cscript%3E",
            "/page/abc",
            "/page/99999999999999999999",
        ] {
            let response = router(&config, test_state())
                .oneshot(
                    Request::builder()
                        .uri(bad)
                        .body(Body::empty())
                        .expect("request builds"),
                )
                .await
                .expect("router responds");

            assert_eq!(
                response.status(),
                StatusCode::NOT_FOUND,
                "{bad} was rejected by the framework rather than answered"
            );
            let content_type = response
                .headers()
                .get(axum::http::header::CONTENT_TYPE)
                .and_then(|v| v.to_str().ok())
                .unwrap_or_default()
                .to_owned();
            assert!(
                content_type.starts_with("text/html"),
                "{bad} answered {content_type}"
            );

            let body = axum::body::to_bytes(response.into_body(), 1 << 20)
                .await
                .expect("body reads");
            let body = String::from_utf8_lossy(&body);
            assert!(
                body.contains("<!DOCTYPE html>"),
                "{bad} did not render a page"
            );
            assert!(
                !body.contains("<script>"),
                "{bad} reflected its input unescaped"
            );
        }
    }

    #[tokio::test]
    async fn health_and_robots_respond_and_carry_security_headers() {
        use axum::body::Body;
        use axum::http::Request;
        use tower::ServiceExt;

        let config = Config::parse_from(["oxblocks"]);

        let response = router(&config, test_state())
            .oneshot(
                Request::builder()
                    .uri("/health")
                    .body(Body::empty())
                    .expect("request builds"),
            )
            .await
            .expect("router responds");

        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            response
                .headers()
                .get("x-content-type-options")
                .and_then(|v| v.to_str().ok()),
            Some("nosniff"),
            "security headers must be applied to every response"
        );
        assert!(response.headers().get("content-security-policy").is_some());
    }

    /// The headers have to survive a response no route produced. A body over
    /// the limit is rejected by middleware sitting outside the router, so
    /// before the header stack was moved outermost this answer carried none of
    /// them.
    #[tokio::test]
    async fn a_middleware_rejection_carries_the_security_headers_too() {
        use axum::body::Body;
        use axum::http::Request;
        use tower::ServiceExt;

        let config = Config::parse_from(["oxblocks"]);
        let oversized = vec![b'x'; config.max_body_bytes + 1];

        let response = router(&config, test_state())
            .oneshot(
                Request::builder()
                    .method("GET")
                    .uri("/health")
                    .header(axum::http::header::CONTENT_LENGTH, oversized.len())
                    .body(Body::from(oversized))
                    .expect("request builds"),
            )
            .await
            .expect("router responds");

        assert_eq!(
            response.status(),
            StatusCode::PAYLOAD_TOO_LARGE,
            "the body limit should have rejected this before routing"
        );
        assert_eq!(
            response
                .headers()
                .get("x-content-type-options")
                .and_then(|v| v.to_str().ok()),
            Some("nosniff")
        );
        assert!(response.headers().get("content-security-policy").is_some());
    }

    #[tokio::test]
    async fn unknown_paths_are_404_not_500() {
        use axum::body::Body;
        use axum::http::Request;
        use tower::ServiceExt;

        let config = Config::parse_from(["oxblocks"]);
        let response = router(&config, test_state())
            .oneshot(
                Request::builder()
                    .uri("/no/such/page")
                    .body(Body::empty())
                    .expect("request builds"),
            )
            .await
            .expect("router responds");

        assert_eq!(response.status(), StatusCode::NOT_FOUND);
    }
}
